# Generated by Django 3.1.5 on 2021-05-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_contactinfo1_student1_teacher1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd1', models.CharField(max_length=20)),
                ('fd2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Child1',
            fields=[
                ('parent1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testApp.parent1')),
                ('fd3', models.CharField(max_length=30)),
                ('fd4', models.CharField(max_length=30)),
            ],
            bases=('testApp.parent1',),
        ),
        migrations.CreateModel(
            name='SubChild',
            fields=[
                ('child1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testApp.child1')),
                ('fd5', models.CharField(max_length=30)),
            ],
            bases=('testApp.child1',),
        ),
    ]
