# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_contactinfo_student_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='ContactInfo1',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Student1',
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teacher1',
        ),
        migrations.RenameField(
            model_name='student1',
            old_name='contactinfo_ptr',
            new_name='contactinfo1_ptr',
        ),
        migrations.RenameField(
            model_name='teacher1',
            old_name='contactinfo_ptr',
            new_name='contactinfo1_ptr',
        ),
    ]
