# Generated by Django 3.1.5 on 2021-04-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bangljobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chennjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hydjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='punejobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
